---
- name: Install Tomcat on Centos
  hosts: tomcat
  become: yes
  tasks:
  - name: Update the system
    yum:
      name: "*"
      state: latest

  - name: Install Java
    yum:
      name: java-1.8.0-openjdk
      state: present

  - name: Download Tomcat
    get_url:
      url: http://www-us.apache.org/dist/tomcat/tomcat-9/v9.0.31/bin/apache-tomcat-9.0.31.tar.gz
      dest: /tmp/tomcat.tar.gz

  - name: Extract Tomcat
    unarchive:
      src: /tmp/tomcat.tar.gz
      dest: /opt/

  - name: Create Tomcat symlink
    file:
      src: /opt/apache-tomcat-9.0.31
      dest: /opt/tomcat
      state: link

  - name: Add Tomcat to Environment Variables
    lineinfile:
      dest: /etc/environment
      line: "CATALINA_HOME=/opt/tomcat"
      state: present
      insertafter: EOL

       name: 
    file:
      src: /opt/apache-tomcat-9.0.31
      dest: /opt/tomcat
      state: link

- name: Deploy Time Display Script
  hosts: tomcat
  become: yes
  tasks:
  - name: Copy script to servers
    copy:
      src: /path/to/time-display.sh
      dest: /usr/local/bin/
      mode: 0755

  - name: Make script executable
    file:
      path: /usr/local/bin/time-display.sh
      mode: 0755

- name: Schedule time display script
  hosts: tomcat
  become: yes
  tasks:
  - name: Create cron job
    cron:
      name: Display current time
      job: "/usr/local/bin/time-display.sh"
      minute: "*/2"
...