---
- name: Deploy Time Display Script
  hosts: g1
  become: yes
  tasks:
  - name: Copy script to servers
    copy:
      src: /path/to/time-display.sh
      dest: /usr/local/bin/
      mode: 0755

  - name: Make script executable
    file:
      path: /usr/local/bin/time-display.sh
      mode: 0755

- name: Schedule time display script
  hosts: tomcat
  become: yes
  tasks:
  - name: Create cron job
    cron:
      name: Display current time
      job: "/usr/local/bin/time-display.sh"
      minute: "*/2"
...

